apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-platform.fullname" . }}
  labels:
    {{- include "devops-platform.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    # Порт для Бэкенда (API)
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: backend
      nodePort: 30080
    # Порт для Фронтенда (Web-интерфейс)
    - port: 80
      targetPort: 80
      protocol: TCP
      name: frontend
      nodePort: 30081
  selector:
    {{- include "devops-platform.selectorLabels" . | nindent 4 }}
    app: backend